 
rm(list = ls()) 


#########################################################################################
#                    Function for sample size calculation: getn2                        #
#########################################################################################

nopt <- function (apcs, target, K, psi, correction = TRUE) {
  pL = target/(target + psi * (1 - target))
  pU = target * psi/(1 - target + target * psi)
  sigL = sqrt(target * (1 - target) + pL * (1 - pL) + 2 * pL * (1 - target))
  sigU = sqrt(target * (1 - target) + pU * (1 - pU) + 2 * target * (1 - pU))
  
  n = 1
  while (T) {
    delL = (target - pL + 0.5/n)/sigL
    delU = (pU - target - 0.5/n)/sigU
    del = (delL + delU)/2
    bindex = 1/K + (1 - 1/K) * (2 * pnorm(sqrt(n) * del) - 1)
    if (bindex >= apcs) {
      break
    }
    n = n + 1
  }
  delL = (target - pL + 0.5/n)/sigL
  delU = (pU - target - 0.5/n)/sigU
  del = (delL + delU)/2
  arg = 1 - K * (1 - apcs)/2/(K - 1)
  val = (qnorm(arg)/del)^2
  val
}

#nopt(0.6, 0.2, 4, 1.6, correction = TRUE)
 

getn2 <- function (apcs, target, K, psi, m) { 
  if (m==1) {lterm = (log(apcs/(1 - apcs)) - 1.8878 + 0.0029 * K^2 + 0.6342 * psi + 1.4600/psi + 0.8454 * target^2)/0.9147}
  if (m==2) {lterm = (log(apcs/(1 - apcs)) - 1.5507 + 0.0039 * K^2 + 0.5402 * psi + 1.1439/psi + 1.5004 * target^2)/0.9333}
  if (m==3) {lterm = (log(apcs/(1 - apcs)) - 1.5400 + 0.0622 * K   + 0.4841 * psi + 0.9657/psi + 1.8155 * target^2)/0.9361}
  if (m==4) {lterm = (log(apcs/(1 - apcs)) - 1.2790 + 0.0063 * K^2 + 0.4693 * psi + 0.8585/psi + 2.0485 * target^2)/0.9452}
  b = exp(lterm)/(1 + exp(lterm))
  na = nopt(b, target, K, psi, correction = correction)  
  ceiling(na)
} 

# getn2(0.6, 0.25, 5, 1.8,1)
# getn2(0.6, 0.25, 5, 1.8,2)
# getn2(0.6, 0.25, 5, 1.8,3)
# getn2(0.6, 0.25, 5, 1.8,4)

#########################################################################################
#                                 Generate Table 5                                      #
#########################################################################################
m.mat <- c(rep(1, 150), rep(2, 150), rep(3, 150),rep(4, 150))
a.mat <- rep(c( rep(0.5,75), rep(0.6, 75)), 4)
R.mat <- rep(c(rep(1.6, 25), rep(1.8, 25),rep(2.0, 25)),8)
theta.mat <-  rep(c( rep(0.1,5), rep(0.15, 5), rep(0.2, 5), rep(0.25, 5), rep(0.3, 5)), 24)
K.mat <- rep(c(4:8), 120)
 
tempn <- mapply(getn2, a.mat, theta.mat, K.mat, R.mat, m.mat)
 
n.m1 <- tempn[1:150]
n.m2 <- tempn[151:300]
n.m3 <- tempn[301:450]
n.m4 <- tempn[451:600]

table5.1 <- cbind(rep(4:8, 5), matrix(n.m1, ncol = 6))
table5.2 <- cbind(rep(4:8, 5), matrix(n.m2, ncol = 6))
table5.3 <- cbind(rep(4:8, 5), matrix(n.m3, ncol = 6))
table5.4 <- cbind(rep(4:8, 5), matrix(n.m4, ncol = 6))

################### Function for convert R matrix to Latex Table ########################
###   source:   http://www.stat.columbia.edu/~yangfeng/software.html

xtab<-function(x, x2=NULL, caption=NULL, align=NULL, digits=NULL, rownames=NULL, colnames=NULL){
  m=nrow(x)
  n=ncol(x)
  if(!is.null(rownames(x))) rownames=rownames(x)
  if(!is.null(colnames(x))) colnames=colnames(x)
  cat('% latex table generated by xtab function\n')
  cat('%',date(),'\n')
  cat('\\begin{table}[ht]\n')
  if(!is.null(caption))
    cat('\\caption{',caption,'}\n',sep='')
  
  cat('\\begin{center}\n')
  if(is.null(align)) {
    align = 'l'
    for(i in 1:n) align = paste(align,'r',sep='')
  }
  if(nchar(align)==1){
    atmp=align
    for(i in 1:n) align = paste(align,atmp,sep='')
  }
  
  if(is.null(digits)) digits = rep(2,n)
  if(length(digits)==1) digits = rep(digits,n+1)
  cat('\\begin{tabular}{', align,'}\n', sep='')
  cat('\\hline\n')
  if(!is.null(colnames)){
    for(j in 1:n)
      cat('&',colnames[j],sep='')
    cat('\\\\\n\\hline\n')
  }
  for(i in 1:m){
    cat(rownames[i])
    
    for(j in 1:n){
      if(!is.character(x[i,j]))
        cat('&',format(round(x[i,j],digits[j]),nsmall=digits[j]),sep='')
      else  cat('&',x[i,j],sep='')
      if(!is.null(x2))  {
        if(!is.character(x2[i,j]))
          cat('(',format(round(x2[i,j],digits[j]),nsmall=digits[j]),')',sep='')
        else
          cat('(',x2[i,j],')',sep='')
      }
    }
    cat('\\\\\n')
    
  }
  cat('\\hline\n')
  cat('\\end{tabular}\n')
  cat('\\end{center}\n')
  cat('\\end{table}\n')
}

# Example:
#   xmean=matrix(rnorm(6),2,3)
#   xsd=matrix(rnorm(6),2,3)
#   xtab(xmean,xsd,rownames=c('a','b'),colnames=c('aa','bb','cc'))


############## Latex Tables #############

xtab(table5.1)
xtab(table5.2)
xtab(table5.3)
xtab(table5.4)


